# Generated by Django 5.1 on 2024-08-28 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Instrument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100)),
                ('calibration_date', models.DateField()),
                ('last_maintenance', models.DateField()),
                ('status', models.CharField(max_length=50)),
            ],
        ),
    ]
